apiVersion: phylake.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  applicationOwner: a-hat
  securityLevel: public
  stages:
    - name: stage1
      cluster:
        repository: https://github.com/a-hat/cluster-test
        name: cluster-test
      resources:
        path: apps
      targetNamespace: app
