apiVersion: securitytower.io/v1alpha1
kind: Application
metadata:
  name: cache-test
spec:
  applicationOwner: "https://github.com/a-hat/cluster-test/blob/main/cluster/namespaces/sbx/cpl15388"
  securityLevel: internal
  stages:
    - name: sbx
      cluster:
        repository: https://github.com/a-hat/cluster-test.git
        name: dev
      resources:
        path: cluster/namespaces/sbx/cpl
      targetNamespace: sbx-cpl
