apiVersion: securitytower.io/v1alpha1
kind: Application
metadata:
  name: cache-test
spec:
  applicationOwner: andreas.kappler@syncier.com
  securityLevel: internal
  stages:
    - name: sbx
      cluster:
        repository: https://github.com/a-hat/cluster-test
        name: dev
      resources:
        path: cluster/namespaces/sbx/cpl5806
      targetNamespace: sbx-cpl
