apiVersion: constraints.gatekeeper.sh/v1beta1
kind: imageallowlist
metadata:
  name: imageallowlist
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-100"
spec:
  # Example of how to configure the global allowlist:
  #
  parameters:
  #   trustedregistries:
  #     - trusted.registry.com
  #     - another.registry.com/my-repo
    trustedimages:
      - busybox
  #     - trusted-image
  #     - trusted-image-with-version:v1.0
  match:
    kinds:
      - apiGroups: ["", "apps", "batch"]
        kinds:
          [
            "Pod",
            "CronJob",
            "ReplicaSet",
            "ReplicationController",
            "Deployment",
            "StatefulSet",
            "DaemonSet",
            "Job",
          ]
